### ISSUE TITLE
Defining unit process variables

### ISSUE THREAD

**Issue by ethan92429** [AguaClara/aguaclara#3]
We need to define what variables AIDE design needs to produce. This will define the interface between aide_design and aide_draw. aide_design should produce everything necessary to build the flocculator, for instance, in a simple to understand way using JSON. First step is to collect ALL the variables that the MathCAD sheets produce and trying to construct a JSON for each unit process. That JSON will be the goal for aide_design, and the input for aide_draw. I suggest making a spreadsheet that has the original mathCAD variable name, the new python variable name (as defined in the standard naming protocol, which should be adapted to the AguaClara use case) and the suggested new 'place'/field of the UP object. For example:

| MathCAD name     | Python Name           | Python location  |   Human readable |
| ------------- |:-------------:| -----:|---:|
| LFiManBranch      | length | filter.manifold.branch.length | length of filter manifold branch |

This would be a very useful document for all the aide packages! And could be used as the official collection of all variables. The JSON file would then look something like this:

{  "result": {
    "unit_process": "filter",
    "name":"filter-Zamorano plant",
    "manifold":{
      "branch":{
          "length":{
             "magnitude":20,
            "units":"cm"
           }
       }
    }
  }
}

**Comment by ethan92429** [comment]
(From Monroe)
Hey,

I was thinking this morning about the JSON database for variables and their values so that all of the aide teams could work independently by having a database that is already populated. I don't know if you've discussed this, but this database is already created by the ADT. See http://designserver.cee.cornell.edu/Designs/EtFlocSedFi/7667/357746449953/About.html.

And if that is missing variables, all you need to do is display the variables that you want in the top level Mathcad code.

My proposal is that someone convert all of the variable names, make sure they are the correct variables to be shared between components of the aide_design, and then fill the JSON database with values from a particular design from the ADT. 

Does this make sense?

Best,

Monroe Weber-Shirk

**Comment by fletchapin** [comment]
@ethan92429 are we ever doing this or is it unnecessary now that we are using classes?

**Comment by eak24** [comment]
We aren't using JSON.
