### ISSUE TITLE
Test the design process using the flocculator

### ISSUE THREAD

**Issue by fletchapin** [AguaClara/aguaclara#60]
Since both us and AIDE Template are done with the flocculator unit process, we will use it to test the integration of both subteam's work to produce a parameterized flocculator based off of user inputs

**Comment by fletchapin** [comment]
@ethan92429 We have nested our classes and it's working well except for that in order to extract types correctly we have to add the ```DP``` tag to the subclasses. However when we do this because it assumes it's a quantity and then cannot access the inner dictionary.

Is there a way to recursively unwrap the classes into dictionaries? Or maybe we could use a separate flag for subclasses vs. attributes

**Comment by ethan92429** [comment]
Extract types is built with this use case in mind - just add the dict as a type on which you'd like to recurse, and extact types will recurse on that type. See [here](https://github.com/AguaClara/aide_render/blob/master/aide_render/builder.py) I'm writing a function, called render_design that automatically renders only the design (DP) parameters so you don't have to worry about extract_types (that is more for internal referencing.) So as soon as I push the next update, you'll be able to call render_design(component_instance) and it'll return a yaml'd version of the component instance. Does that sound good?

**Comment by zoemaisel** [comment]
When we tried to just add dict by doing ```extract_types(my/floc, [DP], [dict]``` , it did not work. When we added ```dict(vars(Class))``` inside the flocculator class definition, it then worked. Is that the intended functionality or do you want this method (```extract_types(my/floc, [DP], [dict]```) to work by itself?

Also, render_design sounds good.

**Comment by ethan92429** [comment]
Interesting... I wonder why it works for the LFOM code? 
```python
>>> my_lfom = LFOM(HP(20, u.L/u.s))
>>> from aide_render.builder import extract_types
>>> lfom_design_dict = extract_types(my_lfom, [DP], [])
>>> #print(lfom_design_dict)
>>> from aide_render.yaml import load, dump
>>> dump(lfom_design_dict)
```

**Comment by fletchapin** [comment]
We have updated the floc class so it's ready to be tested, but we're waiting for AIDE Draw to modify their tool before we could go ahead with the test.

This should be a priority in the fall. Steps to move forward:
1) Download new YAML from Fusion
2) Modify floc class so it aligns with the new YAML
3) Use the class to create an output YAML
4) Use AIDE Draw's tool to update the Fusion model with the output YAML

**Comment by eak24** [comment]
This is irrelevant now.
