### ISSUE TITLE
Update attribute section in class dosctring

### ISSUE THREAD

**Issue by zoemaisel** [AguaClara/aguaclara#65]
Update it to include returns. Look up how to do this in classes.

**Comment by zoemaisel** [comment]
Also include a brief overview of the design algorithm in the docstring

**Comment by fletchapin** [comment]
This is already done in the [floc class](https://github.com/AguaClara/aide_design/blob/filter_design/aide_design/designs/civil_work/floc.py)

**Comment by eak24** [comment]
Irrelevant to new system
