### ISSUE TITLE
Fully test the library

### ISSUE THREAD

**Issue by ethan92429** [AguaClara/aguaclara#7]
We need to have this library FULLY TESTED. Unfortunately, tests weren't written as the code was written (except for those tests that were written thankfully! (in /tests/) We need to finish writing tests to make sure the whole codebase (or at least >80%) is covered by tests (in codecov).

**Comment by ethan92429** [comment]
Test using [doctest](https://gist.github.com/ethan92429/bdb61ccdf352e1fbf560e80dc5ee4481)

**Comment by eak24** [comment]
We've got 80+% coverage.
