### ISSUE TITLE
Create decorator function for subclasses

### ISSUE THREAD

**Issue by zoemaisel** [AguaClara/aguaclara#79]
Most subclasses simply take in a couple of attributes and use the DP wrapper. This process could be improved by creating a single function that takes in any variable and wraps it. 

For example, in ```bottom_baffle.py```
 ```
        self.Height = DP(L_bottom_baffle.magnitude, L_bottom_baffle.units)
        self.Thickness = DP(baffle_thickness.magnitude, baffle_thickness.units)
        self.Width = DP(W_chan.magnitude, W_chan.units)
```
this is repetitive and clunky!

**Comment by eak24** [comment]
Irrelevant to new system
