### ISSUE TITLE
redefinition of RATIO_JET_ROUND and RATIO_JET_PLANE

### ISSUE THREAD

**Issue by monroews** [AguaClara/aguaclara#83]
These two constants are not referenced anywhere in our code base yet. I'm changing their definition to be consistent with the friction factor notation.  Their new values are given below.

#The influence of viscosity on mixing in jet reactors
RATIO_JET_ROUND = 0.08

#This is an estimate for plane jets as created in the flocculator and
# in the sed tank jet reverser.
RATIO_JET_PLANE =0.0124

**Comment by eak24** [comment]
Is this done?

**Comment by monroews** [comment]
I didn't edit these values in the constants file.

**Comment by oliver-leung** [comment]
@monroews @ethan92429 This has been done on the `refactor_names` branch.

For context, what does "round" in RATIO_JET_ROUND mean?

**Comment by monroews** [comment]
Round means it is for a jet coming out of a round pipe or orifice. 
We also have a RATIO_JET_PLANE which means it is a jet that has a width and is infinitely long in the other direction. Okay... not quite that long, but as long as an AguaClara sedimentation tank.
