### ISSUE TITLE
water viscosity and density should be removed from this file

### ISSUE THREAD

**Issue by monroews** [AguaClara/aguaclara#84]
Water viscosity and density should both be a function of temperature. I believe the functional relationship is already defined elsewhere in our code base. These constants should be deleted.

**Comment by fletchapin** [comment]
@monroews which file is it that defines viscosity and density directly? 

I believe that we used the physchem functions which take temperature as an input to find viscosity and density everywhere in the calculations.

**Comment by monroews** [comment]
right. so we should always use those pc functions that take temperature as an input. There shouldn't be a constant value for viscosity and density.

**Comment by eak24** [comment]
Was this ever done?
