### ISSUE TITLE
Numpy version changes outputs in lfom.py

### ISSUE THREAD

**Issue by oliver-leung** [AguaClara/aguaclara#86]
We were running pytest on functions/lfom.py, and we found a strange failure with four of the functions (flow_ramp, height_lfom_orfices, n_lfom_orfices, n_lfom_orfices_fusion).

Here is one of the functions in question:
```
@u.wraps(u.m, [u.m**3/u.s, u.m], False)
def height_lfom_orifices(Q, hl, drill_bits=mat.DIAM_DRILL_ENG):
    """Calculates the height of the center of each row of orifices.
    The bottom of the bottom row orifices is at the zero elevation
    point of the LFOM so that the flow goes to zero when the water height
    is at zero.

    Parameters
    ----------
    Q: float
        flow through the LFOM

    hl : float
        headloss through the LFOM

    drill_bits: array of floats
        an array of potential drill bit sizes to create the orifices

    Returns
    -------
    float
        height of each row from the base of the LFOM

    Examples
    --------
    >>> from aide_design.play import*
    >>> height_lfom_orifices(20*u.L/u.s, 20*u.cm, mat.DIAM_DRILL_ENG)
    <Quantity([ 0.0111125  0.0361125  0.0611125  0.0861125  0.1111125  0.1361125
      0.1611125  0.1861125], 'meter')>

    """
    return (np.arange((orifice_diameter(Q, hl, drill_bits).magnitude*0.5),
                      hl,
                      (dist_center_lfom_rows(Q, hl)).magnitude))
```
Running `pytest lfom.py --doctest-modules -v` gives the following failure:
```
Expected:
    <Quantity([ 0.0111125  0.0361125  0.0611125  0.0861125  0.1111125  0.1361125  0.1611125  0.1861125], 'meter')>
Got:
    <Quantity([0.0111125 0.0361125 0.0611125 0.0861125 0.1111125 0.1361125 0.1611125 0.1861125], 'meter')>
```
A similar failure happens in three other functions, where there is an extra space added to the front of each value. We found that functions for creating lists of values in `numpy` version <= 1.13 add these extra spaces in front of the values, and that version 1.14 doesn't add extra spaces.

When distributing `aide_design`, we'll have to take this into account with our dependencies and specify that `numpy` must be version 1.14 (unless there's some reason to use 1.13?).

**Comment by ethan92429** [comment]
This is good. We should be locking down versions within install_requires.

**Comment by eak24** [comment]
no longer necessary with pipenv specifying our environment.
